#!/bin/bash

read -p "Warning following operations erase all docker images and containers! Press Enter To Continue..."

#kills all containers
docker kill $(docker ps -q)
#deletes all containers
docker rm $(docker ps -a -q)
#deletes all images
docker rmi $(docker images -q)
